// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2GFoM-dCME9BtW2kpQn-i4qDHlHt_BpI',
    appId: '1:1022769972524:web:f43cb66e29178914c75889',
    messagingSenderId: '1022769972524',
    projectId: 'loginpage-90212',
    authDomain: 'loginpage-90212.firebaseapp.com',
    storageBucket: 'loginpage-90212.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuTcmrY5AsiQ-o0ddBB-EssqmIyYlRdL8',
    appId: '1:1022769972524:android:0dc4e737f5c3c26ec75889',
    messagingSenderId: '1022769972524',
    projectId: 'loginpage-90212',
    storageBucket: 'loginpage-90212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0FKHFO-uTWaEC9YAPGI-V23YuIrYfn38',
    appId: '1:1022769972524:ios:e13cfcfc79ca6a13c75889',
    messagingSenderId: '1022769972524',
    projectId: 'loginpage-90212',
    storageBucket: 'loginpage-90212.appspot.com',
    iosBundleId: 'com.example.saharapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0FKHFO-uTWaEC9YAPGI-V23YuIrYfn38',
    appId: '1:1022769972524:ios:34a5a221989249ecc75889',
    messagingSenderId: '1022769972524',
    projectId: 'loginpage-90212',
    storageBucket: 'loginpage-90212.appspot.com',
    iosBundleId: 'com.example.saharapp.RunnerTests',
  );
}
